### Numpy practice

In [1]:
import numpy as np

In [7]:
import numpy as np

# Creating a large array with 1000 elements
nums = np.random.randint(1, 1000, size=1000)  # Random integers between 1 and 1000

print("Array Size:", nums.size)
print("Shape:", nums.shape)
print("Data Type:", nums.dtype)

Array Size: 1000
Shape: (1000,)
Data Type: int64


In [8]:
#Type of the nums array 

print(type(nums))

<class 'numpy.ndarray'>


In [13]:
import numpy as np

# Set the dimensions of the array
rows, cols = 10, 10
nums_2d = np.random.randint(1, 1001, size=(rows, cols))

print("Array Size:", nums_2d.size)
print("Shape:", nums_2d.shape)


Array Size: 100
Shape: (10, 10)


Numpy py arrays are stored at a continuous place in memory unlike list.


In [15]:
arr=np.array([1,2,3,4,5],ndmin=5)

print(arr.shape)
print(arr)

(1, 1, 1, 1, 5)
[[[[[1 2 3 4 5]]]]]


#### Accessing Of Nums-array 2d

In [24]:
print(nums_2d[0:6,3:6])

[[526 484 161]
 [701 821 102]
 [960 510 746]
 [510 742 701]
 [684 854 221]
 [844 988 553]]


In [27]:
import numpy as np

arr = np.array(['"apple"', "banana", 'cherry'])

print(arr.dtype)

<U7


In [31]:
arr = np.array([1, 2, 3, 4], dtype='U7')

print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U7


In [32]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [35]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [34]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [36]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [39]:
arr_1=nums.reshape(20,50)

In [40]:
arr_1

array([[851, 375, 170, 955, 336, 105, 212, 122, 529, 997, 510, 483, 891,
        896, 993, 429, 843, 185, 339, 627, 383, 834, 150, 168, 395, 905,
        368, 382, 466,   7, 555, 939, 779, 590,  99, 841, 869, 743, 670,
        681,  91, 612, 800, 930, 335, 601, 167, 317, 266, 571],
       [537, 413, 666, 854, 665, 347, 935, 774, 140, 444, 931, 257, 927,
         79, 566, 490, 426, 668, 736, 952, 430, 290,  93,  14, 361, 913,
        291, 926, 729, 195, 363, 756, 402,  43, 588,  44, 764, 246,  84,
        849, 456, 520, 590, 920, 742, 756, 131, 930, 167, 650],
       [ 35, 195,  96, 910, 869, 292, 690, 775,  70, 695, 169, 942, 410,
        695, 732, 307,  46, 346, 414, 205, 487, 862, 313, 953, 955, 621,
        863, 985,  97, 661, 913, 726, 892, 114, 776, 626, 246, 306, 483,
        990,  39, 860, 730, 794, 129, 379, 302, 807, 125, 131],
       [575, 253, 498, 941,   5,  14, 634, 854, 997, 278, 298, 679,  39,
        967, 211, 660, 199, 946, 898, 862, 970, 299,  84, 739, 993, 190,
     

In [41]:
new_arr_1=arr_1.reshape(-1)

In [42]:
new_arr_1

array([851, 375, 170, 955, 336, 105, 212, 122, 529, 997, 510, 483, 891,
       896, 993, 429, 843, 185, 339, 627, 383, 834, 150, 168, 395, 905,
       368, 382, 466,   7, 555, 939, 779, 590,  99, 841, 869, 743, 670,
       681,  91, 612, 800, 930, 335, 601, 167, 317, 266, 571, 537, 413,
       666, 854, 665, 347, 935, 774, 140, 444, 931, 257, 927,  79, 566,
       490, 426, 668, 736, 952, 430, 290,  93,  14, 361, 913, 291, 926,
       729, 195, 363, 756, 402,  43, 588,  44, 764, 246,  84, 849, 456,
       520, 590, 920, 742, 756, 131, 930, 167, 650,  35, 195,  96, 910,
       869, 292, 690, 775,  70, 695, 169, 942, 410, 695, 732, 307,  46,
       346, 414, 205, 487, 862, 313, 953, 955, 621, 863, 985,  97, 661,
       913, 726, 892, 114, 776, 626, 246, 306, 483, 990,  39, 860, 730,
       794, 129, 379, 302, 807, 125, 131, 575, 253, 498, 941,   5,  14,
       634, 854, 997, 278, 298, 679,  39, 967, 211, 660, 199, 946, 898,
       862, 970, 299,  84, 739, 993, 190, 108, 816,  48, 191, 56

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [44]:
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [45]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [46]:
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [47]:

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [48]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


axis=0 → stacks arrays vertically (row-wise).
axis=1 → stacks arrays horizontally (column-wise)

In [50]:
arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([[5, 6], 
                 [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [52]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6,7])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [66]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 5)

print(x)

0


In [67]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [68]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [69]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]
